name: tasks_flutter
description: Upwork query task
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_colorpicker: ^1.0.3
  font_awesome_flutter: ^10.1.0
  circular_countdown_timer: ^0.2.1
  stop_watch_timer: ^1.5.0
  sembast: ^3.0.2
  path_provider: ^2.0.7
  flutter_spinkit: ^5.1.0

flutter:
  uses-material-design: true
